#____________________________________________________________________________________________
# change_collision_sensitivity
#____________________________________________________________________________________________

int8 sensitivity   # 0 ~ 100 
---
bool success