#____________________________________________________________________________________________
# servo off
# STOP_TYPE_QUICK_STO = 0,
# STOP_TYPE_QUICK,
# STOP_TYPE_SLOW,
# STOP_TYPE_HOLD,
# STOP_TYPE_EMERGENCY = STOP_TYPE_HOLD,
#____________________________________________________________________________________________

int8 STOP_TYPE_QUICK_STO = 0
int8 STOP_TYPE_QUICK = 1
int8 STOP_TYPE_SLOW = 2
int8 STOP_TYPE_HOLD = 3
int8 STOP_TYPE_EMERGENCY = 3

int8 stop_type     
---
bool success