#____________________________________________________________________________________________
# set_safety_mode
# safety_mode:
# 0: SAFETY_MODE_MANUAL
# 1: SAFETY_MODE_AUTONOMOUS
# 2: SAFETY_MODE_RECOVERY
# 3: SAFETY_MODE_BACKDRIVE
# 4: SAFETY_MODE_MEASURE
# 5: SAFETY_MODE_INITIALIZE
# safety_event:
# 0: SAFETY_MODE_EVENT_ENTER
# 1: SAFETY_MODE_EVENT_MOVE
# 2: SAFETY_MODE_EVENT_STOP
# 3: SAFETY_MODE_EVENT_LAST
#____________________________________________________________________________________________

int8 safety_mode
int8 safety_event
---
bool success