#____________________________________________________________________________________________
# read_data_rt
#____________________________________________________________________________________________

---
RobotStateRt       data