# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 1.7453
    has_acceleration_limits: true
    max_acceleration: 1.7453
    min_position: -3.14
    max_position: 3.14
  joint_2:
    has_velocity_limits: true
    max_velocity: 1.7453
    has_acceleration_limits: true
    max_acceleration: 1.7453
    min_position: -1.6581
    max_position: 1.6581 
  joint_3:
    has_velocity_limits: true
    max_velocity: 2.618
    has_acceleration_limits: true
    max_acceleration: 2.618
    min_position: -2.5307
    max_position: 2.5307
  joint_4:
    has_velocity_limits: true
    max_velocity: 3.927
    has_acceleration_limits: true
    max_acceleration: 3.927
    min_position: -3.14
    max_position: 3.14
  joint_5:
    has_velocity_limits: true
    max_velocity: 3.927
    has_acceleration_limits: true
    max_acceleration: 3.927
    min_position: -2.3562
    max_position: 2.3562
  joint_6:
    has_velocity_limits: true
    max_velocity: 3.927
    has_acceleration_limits: true
    max_acceleration: 3.927
    min_position: -3.14
    max_position: 3.14
